name: wananandroidflutter
description: wanandroid Flutter App实现版本

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2 # iOS风格图标
  # 网络请求框架
  dio: ^3.0.4
  # json注解
  json_annotation: ^3.0.0
  flutter_webview_plugin: ^0.3.8
  banner: ^0.1.3
  cached_network_image: ^1.1.3
  #  flutter_svg: ^0.6.1+1
  url_launcher: 5.2.5
  # toast
  fluttertoast: ^3.1.0
  # SharedPreferences
  shared_preferences: ^0.5.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # json序列化反序列化
  # 配合工具：https://caijinglong.github.io/json2dart/index_ch.html
  json_serializable: ^3.0.0

  # 生成Dart代码文件
  # 配合使用命令：flutter packages pub run build_runner build
  # 配合使用命令：flutter packages pub run build_runner watch
  build_runner: ^1.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
